book_review_user:
    resource: "@BookReviewUserBundle/Resources/config/routing.yml"
    prefix:   /

BookReviewBookBundle:
    resource: "@BookReviewBookBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
