book_api:
    type:     rest
    resource: "@BookReviewAPIBundle/Resources/config/routing.yml"
    prefix:   /api/v1

book_review_user:
    resource: "@BookReviewUserBundle/Resources/config/routing.yml"
    prefix:   /

BookReviewBookBundle:
    resource: "@BookReviewBookBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
