<?php

namespace BookReview\BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
//    public function getBooks($limit, $offset){
//        $queryBuilder = $this->createQueryBuilder('book');
//        $queryBuilder->setFirstResult($offset)
//                     ->setMaxResults($limit);
//
//        $query = $queryBuilder->getQuery();
//
//        return $query->getResult();
//    }

    public function findBookByGenre($query){
        $qb = $this->createQueryBuilder('book')
            ->select('book')
            ->where('book.genre = :query')
            ->setParameter('query', $query);

         $qb->getQuery()
            ->getResult();
    }
}
