<?php

namespace BookReview\BookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends EntityRepository
{
    public function getReviewsforBook($bookId){

        $qb = $this->createQueryBuilder('review')
            ->select('review')
            ->where('review.book = :book_id')
            ->addOrderBy('review.datecreated')
            ->setParameter('book_id', $bookId);

        return $qb->getQuery()
            ->getResult();
    }
}
