
index:
    path:     /
    defaults: { _controller: BookReviewBookBundle:Page:index }

bookreview_about:
    pattern: /about
    defaults: { _controller: BookReviewBookBundle:Page:about }
    requirements:
        _method: GET

bookreview_contact:
    pattern: /contact
    defaults: { _controller: BookReviewBookBundle:Page:contact }
    requirements:
        _method: GET

bookreview_books_view:
    path:     /books/view
    defaults: { _controller: BookReviewBookBundle:Book:view }

#routes for edit, delete and create here