
bookreview_home:
    path:     /
    defaults: { _controller: BookReviewBookBundle:Page:index }

bookreview_about:
    pattern: /about
    defaults: { _controller: BookReviewBookBundle:Page:about }
    requirements:
        _method: GET

bookreview_contact:
    pattern: /contact
    defaults: { _controller: BookReviewBookBundle:Page:contact }
    requirements:
        _method: GET

bookreview_books_view:
    path:     /books/view/{id}
    defaults: { _controller: BookReviewBookBundle:Book:view }
    requirements:
        id: \d+

bookreview_books_create:
    path:     /books/create
    defaults: { _controller: BookReviewBookBundle:Book:create }

bookreview_books_edit:
    path:     /books/edit/{id}
    defaults: { _controller: BookReviewBookBundle:Book:edit }
    requirements:
        id: \d+

bookreview_books_delete:
    path:     /books/delete/{id}
    defaults: { _controller: BookReviewBookBundle:Book:delete }
    requirements:
        id: \d+

bookreview_books_filter:
    path: /books/filter/{query}
    defaults: { _controller: BookReviewBookBundle:Book:filter }

bookreview_reviews_create:
    path:     /review/{book_id}
    defaults: { _controller: BookReviewBookBundle:Review:create }
    requirements:
        id: \d+

bookreview_reviews_edit:
    path:     /review/edit/{id}
    defaults: { _controller: BookReviewBookBundle:Review:edit }
    requirements:
        id: \d+





bookreview_search:
    path: /books/search
    defaults: { _controller: BookReviewBookBundle:Book:search }

bookreview_search_results:
    path: /books/search-results
    defaults: { _controller: BookReviewBookBundle:Book:results }