parameters:
    book_review_book.data.class: BookReview\BookBundle\Controller\DataController

services:
    book_review_book.data:
        class: %book_review_book.data.class%
        arguments:
            em: @doctrine.orm.entity_manager
